Repository AngelaGuardia/Crate, pull requests merged in 2020-12, with the labels that each got.

#36 Migrations
  code/api/src/migrations/6-crateProducts.js
  code/api/src/migrations/7-productHistory.js
  code/api/src/migrations/8-updateSubscriptions.js
Labels: backend

#56 Update subscription mutation
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/modules/subscription/model.js
  code/api/src/modules/subscription/mutations.js
  code/api/src/modules/subscription/resolvers.js
  code/api/src/modules/subscription/types.js
  code/api/src/modules/user/tests/userQuery.test.js
Labels: Availability, backend, enhancement

#60 Feature/profile form styling ih
  code/web/src/modules/profileForm/ProfileForm.js
Labels: Display, Profile, frontend

#69 Readme & Bug fix
  README.md
  code/api/package.json
  code/web/src/modules/user/history/History.js
Labels: documentation
